In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns


import unicodedata

In [ ]:
#pd.set_option('display.float_format', '{:,.2f}'.format)

In [3]:
df_import = pd.read_csv("./Data/Raw/datos_chile_import.csv")
df_export = pd.read_csv("./Data/Raw/datos_chile_export.csv")

# Descripción de Importaciones

In [10]:
len(df_import)

1572022

In [8]:
df_import.head()

,tipo_operacion,rubro_empresa,empresa,total_operacion,cantidad_operacion,ticket_promedio,peso_total,capitulo_arancel,descripcion_arancel,cod_pais,pais,cod_via_transporte,via_transporte,año,mes
0,importación,Productos químicos y derivados,1 MI STORE LIMITADA,103.05,1,103.0500,12340.0,30,Productos farmacéuticos,336,CHINA,1,MARITIMO,2025,5
1,importación,Productos químicos y derivados,1 MI STORE LIMITADA,6925.11,2,3462.5550,46220.0,33,Aceites esenciales y resinoides; preparaciones...,336,CHINA,1,MARITIMO,2025,5
2,importación,Productos químicos y derivados,1 MI STORE LIMITADA,4841.05,2,2420.5250,23920.0,34,"Jabones, agentes de superficie orgánicos, prep...",336,CHINA,1,MARITIMO,2025,2
3,importación,Productos químicos y derivados,1 MI STORE LIMITADA,19312.61,4,4828.1525,78410.0,34,"Jabones, agentes de superficie orgánicos, prep...",336,CHINA,1,MARITIMO,2025,5
4,importación,Productos químicos y derivados,1 MI STORE LIMITADA,1851.77,1,1851.7700,18310.0,35,Sustancias albuminoides; almidones modificados...,336,CHINA,1,MARITIMO,2025,5

In [9]:
df_import.describe()

,total_operacion,cantidad_operacion,ticket_promedio,peso_total,capitulo_arancel,cod_pais,cod_via_transporte,año,mes
count,1.572022e+06,1.572022e+06,1.572022e+06,1.572022e+06,1.572022e+06,1.572022e+06,1.572022e+06,1.572022e+06,1.572022e+06
mean,2.197378e+05,8.685542e+00,3.817337e+04,2.841210e+05,6.081610e+01,3.605234e+02,2.528505e+00,2.022875e+03,6.570335e+00
std,3.087678e+06,4.654663e+01,4.434449e+05,6.346625e+06,2.573856e+01,1.273822e+02,1.965707e+00,1.446892e+00,3.439145e+00
min,1.000000e-02,1.000000e+00,5.000000e-03,1.000000e-02,1.000000e+00,1.010000e+02,1.000000e+00,2.021000e+03,1.000000e+00
25%,2.835038e+03,1.000000e+00,1.326674e+03,5.145400e+02,3.900000e+01,2.250000e+02,1.000000e+00,2.022000e+03,4.000000e+00
50%,1.601312e+04,2.000000e+00,4.853392e+03,5.566000e+03,7.000000e+01,3.360000e+02,1.000000e+00,2.023000e+03,7.000000e+00
75%,7.269023e+04,6.000000e+00,1.881143e+04,4.098695e+04,8.400000e+01,5.070000e+02,4.000000e+00,2.024000e+03,1.000000e+01
max,7.669896e+08,5.927000e+03,1.439333e+08,1.727982e+09,9.700000e+01,9.970000e+02,7.000000e+00,2.025000e+03,1.200000e+01

# Descripción de Importaciones

In [11]:
len(df_export)

428046

In [12]:
df_export.head()

,tipo_operacion,rubro_empresa,empresa,total_operacion,cantidad_operacion,ticket_promedio,peso_total,capitulo_arancel,descripcion_arancel,cod_pais,pais,cod_via_transporte,via_transporte,año,mes
0,exportación,Productos vegetales,365 FRESH SPA,3787426.00,38,99669.105263,808689.43,8,Fruta comestible y frutos secos; cáscara de cí...,336,CHINA,1,MARITIMO,2025,12
1,exportación,Productos químicos y derivados,3M CHILE S A,86286.03,1,86286.030000,530.00,30,Productos farmacéuticos,563,ALEMANIA,1,MARITIMO,2025,6
2,exportación,Productos químicos y derivados,3M CHILE S A,31599.00,1,31599.000000,2529.00,35,Sustancias albuminoides; almidones modificados...,202,COLOMBIA,1,MARITIMO,2025,6
3,exportación,Productos químicos y derivados,3M CHILE S A,27701.57,1,27701.570000,2279.50,35,Sustancias albuminoides; almidones modificados...,202,COLOMBIA,1,MARITIMO,2025,11
4,exportación,Productos químicos y derivados,3M CHILE S A,34768.00,1,34768.000000,3080.00,35,Sustancias albuminoides; almidones modificados...,219,PERU,1,MARITIMO,2025,5

In [6]:
df_export.describe()

,total_operacion,cantidad_operacion,ticket_promedio,peso_total,capitulo_arancel,cod_pais,cod_via_transporte,año,mes
count,4.280460e+05,428046.000000,4.280460e+05,4.280460e+05,428046.000000,428046.000000,428046.000000,428046.000000,428046.000000
mean,1.080629e+06,11.259851,2.011587e+05,7.291811e+05,32.967015,294.421576,2.553819,2022.982782,6.490725
std,1.175077e+07,60.917296,1.830471e+06,1.506533e+07,27.074773,116.748047,2.388465,1.425833,3.433804
min,1.000000e-02,1.000000,1.000000e-02,0.000000e+00,1.000000,101.000000,1.000000,2021.000000,1.000000
25%,1.477414e+04,1.000000,4.525728e+03,1.981000e+03,8.000000,219.000000,1.000000,2022.000000,4.000000
50%,5.974985e+04,3.000000,1.846558e+04,2.171400e+04,22.000000,224.000000,1.000000,2023.000000,6.000000
75%,2.208741e+05,8.000000,5.184409e+04,8.448000e+04,44.000000,335.000000,4.000000,2024.000000,9.000000
max,1.404970e+09,7673.000000,1.999955e+08,1.815028e+09,97.000000,565.000000,7.000000,2025.000000,12.000000

In [13]:
df_export.dtypes

tipo_operacion             str
rubro_empresa              str
empresa                    str
total_operacion        float64
cantidad_operacion       int64
ticket_promedio        float64
peso_total             float64
capitulo_arancel         int64
descripcion_arancel        str
cod_pais                 int64
pais                       str
cod_via_transporte       int64
via_transporte             str
año                      int64
mes                      int64
dtype: object

In [22]:
#Con las fuentes separadas este campo ya no hace falta
df_export = df_export.drop(columns=["tipo_operacion"])
df_import = df_import.drop(columns=["tipo_operacion"])

In [26]:
#Mismas columnas para ambas fuentes

#No se incluyen columnas que no representan medidas ( ej: capitulo_arancel )
numerical_cols = [
    "total_operacion",
    "cantidad_operacion",
    "ticket_promedio",
    "peso_total",
]

categorical_cols = [
    "rubro_empresa",
    "empresa",
    "descripcion_arancel",#Quitar antes de entrenar modelo
    "pais",
    "via_transporte"
]

#### Observación: Nombres de columnas ya se encuentran normalizadas. No hay espacios en blancos ni carácteres especiales

# Normalizar valores Categóricos

In [30]:
def formatCategorical(df,categorical_cols):
    for c in categorical_cols:
        df[c] = df[c].str.lower().str.replace(' ', '_')

In [31]:
formatCategorical(df_import,categorical_cols)
formatCategorical(df_export,categorical_cols)

In [32]:
df_import.head()

,rubro_empresa,empresa,total_operacion,cantidad_operacion,ticket_promedio,peso_total,capitulo_arancel,descripcion_arancel,cod_pais,pais,cod_via_transporte,via_transporte,año,mes
0,productos_químicos_y_derivados,1_mi_store_limitada,103.05,1,103.0500,12340.0,30,productos_farmacéuticos,336,china,1,maritimo,2025,5
1,productos_químicos_y_derivados,1_mi_store_limitada,6925.11,2,3462.5550,46220.0,33,aceites_esenciales_y_resinoides;_preparaciones...,336,china,1,maritimo,2025,5
2,productos_químicos_y_derivados,1_mi_store_limitada,4841.05,2,2420.5250,23920.0,34,"jabones,_agentes_de_superficie_orgánicos,_prep...",336,china,1,maritimo,2025,2
3,productos_químicos_y_derivados,1_mi_store_limitada,19312.61,4,4828.1525,78410.0,34,"jabones,_agentes_de_superficie_orgánicos,_prep...",336,china,1,maritimo,2025,5
4,productos_químicos_y_derivados,1_mi_store_limitada,1851.77,1,1851.7700,18310.0,35,sustancias_albuminoides;_almidones_modificados...,336,china,1,maritimo,2025,5

# Revisar datos inválidos

### Nulos

In [33]:
df_import.isna().sum()

rubro_empresa          0
empresa                0
total_operacion        0
cantidad_operacion     0
ticket_promedio        0
peso_total             0
capitulo_arancel       0
descripcion_arancel    0
cod_pais               0
pais                   0
cod_via_transporte     0
via_transporte         0
año                    0
mes                    0
dtype: int64

In [35]:
(df_import == 0).sum()

rubro_empresa          0
empresa                0
total_operacion        0
cantidad_operacion     0
ticket_promedio        0
peso_total             0
capitulo_arancel       0
descripcion_arancel    0
cod_pais               0
pais                   0
cod_via_transporte     0
via_transporte         0
año                    0
mes                    0
dtype: int64

In [36]:
df_export.isna().sum()

rubro_empresa          0
empresa                0
total_operacion        0
cantidad_operacion     0
ticket_promedio        0
peso_total             0
capitulo_arancel       0
descripcion_arancel    0
cod_pais               0
pais                   0
cod_via_transporte     0
via_transporte         0
año                    0
mes                    0
dtype: int64

In [37]:
(df_export == 0).sum()

rubro_empresa          0
empresa                0
total_operacion        0
cantidad_operacion     0
ticket_promedio        0
peso_total             4
capitulo_arancel       0
descripcion_arancel    0
cod_pais               0
pais                   0
cod_via_transporte     0
via_transporte         0
año                    0
mes                    0
dtype: int64

In [38]:
df_export[df_export.peso_total == 0]

,rubro_empresa,empresa,total_operacion,cantidad_operacion,ticket_promedio,peso_total,capitulo_arancel,descripcion_arancel,cod_pais,pais,cod_via_transporte,via_transporte,año,mes
330937,madera_y_productos_de_madera,vina_carta_vieja_s.a.,160.0,1,160.0,0.0,44,madera_y_artículos_de_madera;_carbón_vegetal,342,hong_kong,1,maritimo,2022,9
419625,madera_y_productos_de_madera,vina_carta_vieja_s.a.,220.0,1,220.0,0.0,44,madera_y_artículos_de_madera;_carbón_vegetal,225,u.s.a,1,maritimo,2021,11
419654,madera_y_productos_de_madera,vina_carta_vieja_s.a.,100.0,1,100.0,0.0,44,madera_y_artículos_de_madera;_carbón_vegetal,342,hong_kong,1,maritimo,2021,11
419655,madera_y_productos_de_madera,vina_carta_vieja_s.a.,50.0,1,50.0,0.0,44,madera_y_artículos_de_madera;_carbón_vegetal,406,australia,1,maritimo,2021,10

### Conclusion sobre nulos:

no hubo ningún valor nulo pero si valores "0" irregulares en el campo peso_total para las exportaciones, 4 entradas para ser espeçífico. Al revisar estas entradas notamos que son operaciones muy pequeñas tanto en cantidad como en total_operacion lo que podría indicar que se puede tratar de operaciones con pesos muy pequeños y el sistema no permitió decimales. En resumen : el valor "0" hace sentido para estas operaciones y no serán eliminados.

### Valores duplicados

In [40]:
df_import.duplicated().sum()

np.int64(0)

In [41]:
df_export.duplicated().sum()

np.int64(0)

### Observación: sin valores duplicados

# Exportar archivos de data procesada

In [42]:
df_import.to_csv("./Data/Processed/processed_datos_chile_import.csv", index=False)
df_export.to_csv("./Data/Processed/processed_datos_chile_export.csv", index=False)